@startuml

package "Sistema de Aluguel de Carros" {

    [Interface Web] -[hidden]-> [Servidor de Aplicação]
    [Servidor de Aplicação] -[hidden]-> [Banco de Dados]
    
    [Interface Web] --> [Gerenciador de Pedidos e Contratos]
    [Interface Web] --> [Autenticação]
    
    [Gerenciador de Pedidos e Contratos] --> [Gerenciador de Veículos]
    [Gerenciador de Pedidos e Contratos] --> [Repositorios de Dados]

    [Autenticação] --> [Repositorios de Dados]

    [Gerenciador de Veículos] --> [Repositorios de Dados]

    [Repositorios de Dados] --> [Banco de Dados]

}

@enduml
