@startuml
top to bottom direction

actor Contratante
actor Agente
actor Usuário

(Usuário Registrado) <|-- (Contratante)
(Usuário Registrado) <|-- (Agente)

(Registrar Usuário) 
(Realizar Login)

(Registrar Pedido de Aluguel)
(Modificar Pedido de Aluguel)
(Consultar Pedido de Aluguel)
(Cancelar Pedido de Aluguel)
(Executar Contrato de Aluguel)
(Avaliar Pedido de Aluguel)
(Registrar Automóvel)
(Associar Contrato de Crédito)

Usuário --> (Registrar Usuário)
Usuário --> (Realizar Login)

Contratante --> (Registrar Pedido de Aluguel)
Contratante --> (Modificar Pedido de Aluguel)
Contratante --> (Consultar Pedido de Aluguel)
Contratante --> (Cancelar Pedido de Aluguel)
Contratante --> (Executar Contrato de Aluguel)

Agente --> (Avaliar Pedido de Aluguel)
Agente --> (Modificar Pedido de Aluguel)
Agente --> (Executar Contrato de Aluguel)
Agente -left-> (Registrar Automóvel)
Agente --> (Associar Contrato de Crédito)

(Executar Contrato de Aluguel) <-left- (Avaliar Pedido de Aluguel): <<include>>
(Executar Contrato de Aluguel) <-- (Registrar Automóvel): <<include>>
@enduml
